=== YeeeeahRight/XmlParser/gems.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://gems.com"
        xmlns:tns="https://gems.com"  elementFormDefault="qualified">

    <element name="gems">
        <complexType>
            <choice minOccurs="0" maxOccurs="unbounded">
                <element name="precious-gem" type="tns:precious-gem"/>
                <element name="semi-precious-gem" type="tns:semi-precious-gem"/>
            </choice>
        </complexType>
    </element>

    <complexType name="precious-gem">
        <complexContent>
            <extension base="tns:abstract-gem">
                <sequence>
                    <element name="carat-weight">
                        <simpleType>
                            <restriction base="decimal">
                                <pattern value="[0-9]{1,10}(\.[0-9]{1,8})?"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="semi-precious-gem">
        <complexContent>
            <extension base="tns:abstract-gem">
                <sequence>
                    <element name="weight">
                        <simpleType>
                            <restriction base="decimal">
                                <pattern value="[0-9]{1,10}(\.[0-9]{1,8})?"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="abstract-gem">
        <sequence>
            <element name="name" type="string"/>
            <element name="origin" type="string"/>
            <element name="hardness">
                <simpleType>
                    <restriction base="decimal">
                        <minInclusive value="1"/>
                        <maxInclusive value="10"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="color" type="string"/>
            <element name="gem-type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Natural"/>
                        <enumeration value="Synthetic"/>
                        <enumeration value="Imitation"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="ID-[1-9][0-9]{0,5}"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
</schema>

=== YeeeeahRight/XmlParser/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://gems.com/ gems.xsd"
          xmlns="https://gems.com">
    <!--First gem-->
    <precious-gem id="ID-1">
        <name>Diamond</name>
        <origin>Australia</origin>
        <hardness>10.0</hardness>
        <color>Colorless</color>
        <gem-type>Natural</gem-type>
        <carat-weight>1.5</carat-weight>
    </precious-gem>
    <!--Second gem-->
    <precious-gem id="ID-2">
        <name>Ruby</name>
        <origin>Myanmar</origin>
        <hardness>9.0</hardness>
        <color>Red</color>
        <gem-type>Synthetic</gem-type>
        <carat-weight>10.32</carat-weight>
    </precious-gem>
    <!--Third gem-->
    <semi-precious-gem id="ID-3">
        <name>Agate</name>
        <origin>Georgia</origin>
        <hardness>6.6</hardness>
        <color>Black</color>	
        <gem-type>Natural</gem-type>
        <weight>21</weight>
    </semi-precious-gem>
    <!--Fourth gem-->
    <semi-precious-gem id="ID-4">
        <name>Amethyst</name>
        <origin>Sri lanka</origin>
        <hardness>7</hardness>
        <color>Violet</color>
        <gem-type>Imitation</gem-type>
        <weight>10.0</weight>
    </semi-precious-gem>
</gems>
